# Generated by Django 4.1.7 on 2023-03-12 08:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useraccount",
            old_name="full_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="useraccount",
            old_name="phone_number",
            new_name="phonenumber",
        ),
    ]
