# Generated by Django 4.1.7 on 2023-03-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_full_name_useraccount_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="image",
            field=models.ImageField(blank=True, upload_to="profiles/"),
        ),
    ]
