# Generated by Django 4.1.7 on 2023-03-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_useraccount_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
